
wandb: WARNING Calling wandb.run.save without any arguments is deprecated.Changes to attributes are automatically persisted.
[ INFO ]: Seeding RNGs with 42
[ INFO ]: Loading DepthODFDatasetLoader dataset. Positional Encoding: False, Coordinate Type: direction, Autodecoder: False
DATA SIZE: 1000
[ INFO ]: Loading DepthODFDatasetLoader dataset. Positional Encoding: False, Coordinate Type: direction, Autodecoder: False
[ INFO ]: Training data has 1000 shapes and 1000 rays per sample.
[ INFO ]: Validation data has 200 shapes and 10 rays per sample.
----------------------------- EPOCH: 1/3 -----------------------------
Training...




 95%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏      | 60/63 [00:09<00:00,  7.50it/s]
Training Loss: 0.83277
Validation...
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 63/63 [00:09<00:00,  6.65it/s]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 13/13 [00:00<00:00, 16.99it/s]
Traceback (most recent call last):
  File "train.py", line 216, in <module>
    train(Args.output_dir, Args.expt_name, NeuralODF, Mask3D, optimizer, TrainDataLoader, ValDataLoader, loss_history, hyperparameters, Device, scheduler)
  File "train.py", line 127, in train
    v5_utils.checkpoint(odf_model, mask_model, save_dir, name, previous_epochs+e, optimizer, loss_history)
  File "F:\DirectedDistanceFunction\v5\v5_utils.py", line 119, in checkpoint
    save_checkpoint(save_dir, checkpoint_dict)
  File "F:\DirectedDistanceFunction\v5\v5_utils.py", line 83, in save_checkpoint
    os.mkdir(os.path.join(save_dir, name))
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'F:/ivl-data/output\\v5_test'